source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.0'
pod 'UIAlertView+Blocks', '~>0.8.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'SVPullToRefresh', '~> 0.4.1'

